//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoutiqueProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int areaid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> stid { get; set; }
        public Nullable<int> cid { get; set; }
        public string areanm { get; set; }
    }
}
