//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoutiqueProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertb
    {
        public int Id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> btid { get; set; }
        public Nullable<int> quantity { get; set; }
        public string odate { get; set; }
        public string address { get; set; }
    }
}
