//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoutiqueProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int pid { get; set; }
        public Nullable<int> catid { get; set; }
        public string pname { get; set; }
        public string pdescription { get; set; }
        public string price { get; set; }
        public string prodpic { get; set; }
        public Nullable<int> btid { get; set; }
        public Nullable<int> subcatid { get; set; }
        public string gender { get; set; }
    }
}
