//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoutiqueProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTb
    {
        public int Id { get; set; }
        public string bname { get; set; }
        public string bpic { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string password { get; set; }
        public Nullable<int> cnid { get; set; }
        public Nullable<int> stid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> areaid { get; set; }
    }
}
